#--------------------------------------------------------
#-- fun_corrige_CUADRO_4_1_anho2017 --
#--------------------------------------------------------
#-- This function was generated by Fn_epidemiologic
#-- Created on: Wed Oct 21 15:10:40 2020
#-- Author = Arrigo Coen 



# Current expected number of columns is: 13

# Number of weeks consider from 1 to 52

# Obs: The commented values are the original, and they are as a reference.

fun_corrige_CUADRO_4_1_anho2017 <- function(text_table,semana,anho) {
	if(semana==3 && anho==2017) {
		i <- 15;
		#México     24    22    21    49    3    4    3    29 10 982    9 448    10 796    18 565
		text_table[i] <- 'México     24    22    21    49    3    4    3    29    10982    9448    10796    18565'
	}
	if(semana==4 && anho==2017) {
		i <- 15;
		#México     45    44    51    79    1    4    4    30 13 308    15 624    18 007    27 846
		text_table[i] <- 'México     45    44    51    79    1    4    4    30   13308    15624    18007    27846'
	}
	if(semana==47 && anho==2017) {
		i <- 15;
		#México     2    620    939    1 641    1    53    83    158 10 117    261 050    302 148    519 134
		text_table[i] <- 'México     2    620    939    1641    1    53    83    158     10117    261050    302148    519134'
	}
	if(semana==49 && anho==2017) {
		i <- 15;
		#México    25    640    975    1 687    -    53    89    166 10 288    270 644    312 755    535 691
		text_table[i] <- 'México    25    640    975    1687    -    53    89    166  10288    270644    312755    535691'
	}
	if(semana==50 && anho==2017) {
		i <- 9;
		#Ciudad de México    8    123    267    457    -    16    20    51 11 449    173 595    203 235    293 380
		text_table[i] <- 'Ciudad de México    8    123    267    457    -    16    20    51    11449    173595    203235    293380'
		i <- 15;
		#México    38    653    1 000    1 705    -    53    89    169 10 635    275 731    318 406    543 959
		text_table[i] <- 'México    38    653    1000    1705    -    53    89    169    10635    275731    318406    543959'
	}
	return(text_table)
}
