#--------------------------------------------------------
#-- fun_corrige_CUADRO_4_1_anho2014 --
#--------------------------------------------------------
#-- This function was generated by Fn_epidemiologic
#-- Created on: Wed Oct 21 14:50:04 2020
#-- Author = Arrigo Coen 



# Current expected number of columns is: 13

# Obs: The commented values are the original, and they are as a reference.

fun_corrige_CUADRO_4_1_anho2014 <- function(text_table,semana,anho) {
	if(semana==1 && anho==2014) {
		i <- 1;
		#Aguascalientes    23    652    1 149   2 902    -    51    59    77
		text_table[i] <- 'Aguascalientes    23    652    1 149   2 902    -    51    59    77'
		i <- 2;
		#Baja California    25    442    818   1 959    -    24    19    102
		text_table[i] <- 'Baja California    25    442    818   1 959    -    24    19    102'
		i <- 3;
		#Baja California Sur    2    66    162    489    -    9    5    25
		text_table[i] <- 'Baja California Sur    2    66    162    489    -    9    5    25'
		i <- 4;
		#Campeche    26    469    943   1 438    4    64    88    231
		text_table[i] <- 'Campeche    26    469    943   1 438    4    64    88    231'
		i <- 5;
		#Coahuila    55    1 920    5 327  10 745    -    19    26    94
		text_table[i] <- 'Coahuila    55    1 920    5 327  10 745    -    19    26    94'
		i <- 6;
		#Colima     -    39    73    133    -    6    9    34
		text_table[i] <- 'Colima     -    39    73    133    -    6    9    34'
		i <- 7;
		#Chiapas    188    6 669    12 872  27 386    3    466    553   1 239
		text_table[i] <- 'Chiapas    188    6 669    12 872  27 386    3    466    553   1 239'
		i <- 8;
		#Chihuahua    25    965    2 793   5 337    -    36    33    56
		text_table[i] <- 'Chihuahua    25    965    2 793   5 337    -    36    33    56'
		i <- 9;
		#Distrito Federal    8    319    456    797    -    36    36    77
		text_table[i] <- 'Distrito Federal    8    319    456    797    -    36    36    77'
		i <- 10;
		#Durango    -    8    28    23    1    69    87    118
		text_table[i] <- 'Durango    -    8    28    23    1    69    87    118'
		i <- 11;
		#Guanajuato    2    228    508    675    -    101    112    379
		text_table[i] <- 'Guanajuato    2    228    508    675    -    101    112    379'
		i <- 12;
		#Guerrero    21    1 140    2 013   4 525    14    511    876   1 221
		text_table[i] <- 'Guerrero    21    1 140    2 013   4 525    14    511    876   1 221'
		i <- 13;
		#Hidalgo    1    82    116    188    -    37    36    19
		text_table[i] <- 'Hidalgo    1    82    116    188    -    37    36    19'
		i <- 14;
		#Jalisco    45    1 003    1 955   4 998    -    109    139    277
		text_table[i] <- 'Jalisco    45    1 003    1 955   4 998    -    109    139    277'
		i <- 15;
		#México    14    629    1 010   2 698    -    123    103    369
		text_table[i] <- 'México    14    629    1 010   2 698    -    123    103    369'
		i <- 16;
		#Michoacán    19    443    880   2 473    -    39    69    109
		text_table[i] <- 'Michoacán    19    443    880   2 473    -    39    69    109'
		i <- 17;
		#Morelos    1    103    176    470    1    23    44    60
		text_table[i] <- 'Morelos    1    103    176    470    1    23    44    60'
		i <- 18;
		#Nayarit    30    718    1 281   2 200    -    42    54    59
		text_table[i] <- 'Nayarit    30    718    1 281   2 200    -    42    54    59'
		i <- 19;
		#Nuevo León    4    233    313   1 332    1    23    30    99
		text_table[i] <- 'Nuevo León    4    233    313   1 332    1    23    30    99'
		i <- 20;
		#Oaxaca    12    593    1 168   2 623    14    373    451   1 017
		text_table[i] <- 'Oaxaca    12    593    1 168   2 623    14    373    451   1 017'
		i <- 21;
		#Puebla    63    1 259    2 368   5 314    1    155    244    511
		text_table[i] <- 'Puebla    63    1 259    2 368   5 314    1    155    244    511'
		i <- 22;
		#Querétaro    1    62    137    548    -    28    16    72
		text_table[i] <- 'Querétaro    1    62    137    548    -    28    16    72'
		i <- 23;
		#Quintana Roo    58    901    1 593   4 652    -    21    24    2
		text_table[i] <- 'Quintana Roo    58    901    1 593   4 652    -    21    24    2'
		i <- 24;
		#San Luis Potosí    33    227    548    915    -    101    101    133
		text_table[i] <- 'San Luis Potosí    33    227    548    915    -    101    101    133'
		i <- 25;
		#Sinaloa    45    727    1 509   5 174    -    62    76    158
		text_table[i] <- 'Sinaloa    45    727    1 509   5 174    -    62    76    158'
		i <- 26;
		#Sonora    7    157    371   1 382    1    20    45    83
		text_table[i] <- 'Sonora    7    157    371   1 382    1    20    45    83'
		i <- 27;
		#Tabasco    49    3 080    6 490  13 133    2    138    204    405
		text_table[i] <- 'Tabasco    49    3 080    6 490  13 133    2    138    204    405'
		i <- 28;
		#Tamaulipas    46    768    1 884   4 825    2    81    115    213
		text_table[i] <- 'Tamaulipas    46    768    1 884   4 825    2    81    115    213'
		i <- 29;
		#Tlaxcala    5    199    471   1 084    2    26    38    32
		text_table[i] <- 'Tlaxcala    5    199    471   1 084    2    26    38    32'
		i <- 30;
		#Veracruz    90    2 669    6 020  15 842    1    196    250    546
		text_table[i] <- 'Veracruz    90    2 669    6 020  15 842    1    196    250    546'
		i <- 31;
		#Yucatán    10    380    516    679    19    51    69    120
		text_table[i] <- 'Yucatán    10    380    516    679    19    51    69    120'
		i <- 32;
		#Zacatecas    17    653    1 115   2 063    -    49    64    129
		text_table[i] <- 'Zacatecas    17    653    1 115   2 063    -    49    64    129'
	}
	if(semana==2 && anho==2014) {
		i <- 1;
		#Aguascalientes    -    -    -    1    1    -    -  1 270    622    648    1 237
		text_table[i] <- 'Aguascalientes    -    -    -    1    1    -    -  1 270    622    648    1 237'
		i <- 2;
		#Baja California    1    -    1    1    -    1    1  1 403    607    796    1 599
		text_table[i] <- 'Baja California    1    -    1    1    -    1    1  1 403    607    796    1 599'
		i <- 3;
		#Baja California Sur    1    -    1    -    -    -    -    359    144    215    346
		text_table[i] <- 'Baja California Sur    1    -    1    -    -    -    -    359    144    215    346'
		i <- 4;
		#Campeche    -    -    -    3    -    3    2    641    305    336    1 493
		text_table[i] <- 'Campeche    -    -    -    3    -    3    2    641    305    336    1 493'
		i <- 5;
		#Coahuila    -    -    -    -    -    -    -  1 234    567    667    2 026
		text_table[i] <- 'Coahuila    -    -    -    -    -    -    -  1 234    567    667    2 026'
		i <- 6;
		#Colima    -    -    -    -    -    -    -    514    255    259    622
		text_table[i] <- 'Colima    -    -    -    -    -    -    -    514    255    259    622'
		i <- 7;
		#Chiapas    2    1    1    8    4    4    7  1 643    767    876    2 390
		text_table[i] <- 'Chiapas    2    1    1    8    4    4    7  1 643    767    876    2 390'
		i <- 8;
		#Chihuahua    -    -    -    2    1    1    1  1 514    654    860    1 912
		text_table[i] <- 'Chihuahua    -    -    -    2    1    1    1  1 514    654    860    1 912'
		i <- 9;
		#Distrito Federal    -    -    -    -    -    -    4  4 644    2 087    2 557    5 082
		text_table[i] <- 'Distrito Federal    -    -    -    -    -    -    4  4 644    2 087    2 557    5 082'
		i <- 10;
		#Durango    -    -    -    1    -    1    26    921    433    488    1 623
		text_table[i] <- 'Durango    -    -    -    1    -    1    26    921    433    488    1 623'
		i <- 11;
		#Guanajuato    -    -    -    -    -    -    12   1 865    892    973    3 147
		text_table[i] <- 'Guanajuato    -    -    -    -    -    -    12   1 865    892    973    3 147'
		i <- 12;
		#Guerrero    3    1    2    17    5    12    18   1 478    659    819    2 470
		text_table[i] <- 'Guerrero    3    1    2    17    5    12    18   1 478    659    819    2 470'
		i <- 13;
		#Hidalgo    2    -    2    1    1    -    1    927    457    470    1 440
		text_table[i] <- 'Hidalgo    2    -    2    1    1    -    1    927    457    470    1 440'
		i <- 14;
		#Jalisco    1    -    1    1    1    -    6  2 935    1 434    1 501    4 225
		text_table[i] <- 'Jalisco    1    -    1    1    1    -    6  2 935    1 434    1 501    4 225'
		i <- 15;
		#México    4    2    2    1    1    -    1  5 907    2 753    3 154    7 330
		text_table[i] <- 'México    4    2    2    1    1    -    1  5 907    2 753    3 154    7 330'
		i <- 16;
		#Michoacán    -    -    -    -    -    -    -  1 829    888    941    2 721
		text_table[i] <- 'Michoacán    -    -    -    -    -    -    -  1 829    888    941    2 721'
		i <- 17;
		#Morelos    1    1    -    2    1    1    1  1 126    509    617    1 246
		text_table[i] <- 'Morelos    1    1    -    2    1    1    1  1 126    509    617    1 246'
		i <- 18;
		#Nayarit    1    1    -    -    -    -    -  1 206    569    637    1 213
		text_table[i] <- 'Nayarit    1    1    -    -    -    -    -  1 206    569    637    1 213'
		i <- 19;
		#Nuevo León    -    -    -    -    -    -    -  2 448    1 151    1 297    3 016
		text_table[i] <- 'Nuevo León    -    -    -    -    -    -    -  2 448    1 151    1 297    3 016'
		i <- 20;
		#Oaxaca    3    2    1    5    2    3    7  2 186    1 002    1 184    3 386
		text_table[i] <- 'Oaxaca    3    2    1    5    2    3    7  2 186    1 002    1 184    3 386'
		i <- 21;
		#Puebla    4    3    1    3    2    1    -  1 975    951    1 024    1 415
		text_table[i] <- 'Puebla    4    3    1    3    2    1    -  1 975    951    1 024    1 415'
		i <- 22;
		#Querétaro    -    -    -    -    -    -    -    815    358    457    1 234
		text_table[i] <- 'Querétaro    -    -    -    -    -    -    -    815    358    457    1 234'
		i <- 23;
		#Quintana Roo    5    1    4    -    -    -    -  1 086    513    573    1 656
		text_table[i] <- 'Quintana Roo    5    1    4    -    -    -    -  1 086    513    573    1 656'
		i <- 24;
		#San Luis Potosí    -    -    -    2    1    1    2    905    405    500    1 350
		text_table[i] <- 'San Luis Potosí    -    -    -    2    1    1    2    905    405    500    1 350'
		i <- 25;
		#Sinaloa    23    9    14    2    -    2    1  1 564    736    828    1 653
		text_table[i] <- 'Sinaloa    23    9    14    2    -    2    1  1 564    736    828    1 653'
		i <- 26;
		#Sonora    1    -    1    -    -    -    1  1 235    540    695    1 307
		text_table[i] <- 'Sonora    1    -    1    -    -    -    1  1 235    540    695    1 307'
		i <- 27;
		#Tabasco    3    2    1    -    -    -    21   1 432    677    755    1 890
		text_table[i] <- 'Tabasco    3    2    1    -    -    -    21   1 432    677    755    1 890'
		i <- 28;
		#Tamaulipas    1    -    1    1    -    1    -  1 446    669    777    2 214
		text_table[i] <- 'Tamaulipas    1    -    1    1    -    1    -  1 446    669    777    2 214'
		i <- 29;
		#Tlaxcala    -    -    -    -    -    -    -    678    308    370    832
		text_table[i] <- 'Tlaxcala    -    -    -    -    -    -    -    678    308    370    832'
		i <- 30;
		#Veracruz    34    14    20    3    1    2    3  2 794    1 314    1 480    4 378
		text_table[i] <- 'Veracruz    34    14    20    3    1    2    3  2 794    1 314    1 480    4 378'
		i <- 31;
		#Yucatán    -    -    -    -    -    -    3  1 413    635    778    1 957
		text_table[i] <- 'Yucatán    -    -    -    -    -    -    3  1 413    635    778    1 957'
		i <- 32;
		#Zacatecas    -    -    -    2    -    2    8    637    273    364    970
		text_table[i] <- 'Zacatecas    -    -    -    2    -    2    8    637    273    364    970'
	}
	return(text_table)
}
