#--------------------------------------------------------
#-- fun_corrige_CUADRO_17_anho2015 --
#--------------------------------------------------------
#-- This function was generated by Fn_epidemiologic
#-- Author = Arrigo Coen 



fun_corrige_CUADRO_17_anho2015 <- function(text_table,semana,anho) {
	if(semana==7 && anho==2015) {
		i <- 30;
		x <- 'Veracruz    84    79    320    319  15    20    17    16    3    5    7    4'
		text_table[i] <- x
	}
	if(semana==8 && anho==2015) {
		i <- 28;
		x <- 'Tamaulipas    78    104    252    282   14    13    10    53    2    1    4    16'
		text_table[i] <- x
	}
	if(semana==10 && anho==2015) {
		i <- 15;
		x <- 'México    96    214    729    929  10    45    39    125    1    8    6    31'
		text_table[i] <- x
		i <- 25;
		x <- 'Sinaloa    48    60    263    229  10    13    15    59    1    4    5    17'
		text_table[i] <- x
	}
	if(semana==32 && anho==2015) {
		i <- 2;
		x <- 'Baja California    39    282  1000    1580    1    53    52    151    2    23    35    68'
		text_table[i] <- x
	}
	if(semana==33 && anho==2015) {
		i <- 2;
		x <- 'Baja California    59    297  1044    1622    3    54    54    156    1    23    36    69'
		text_table[i] <- x
	}
	if(semana==34 && anho==2015) {
		i <- 2;
		x <- 'Baja California    47    401   1427    1677    6    79    82    162    -    30    51    73'
		text_table[i] <- x
	}
	if(semana==35 && anho==2015) {
		i <- 2;
		x <- 'Baja California    54    416   1466    1736    3    79    85    172    1    30    52    79'
		text_table[i] <- x
	}
	if(semana==36 && anho==2015) {
		i <- 2;
		x <- 'Baja California    51    426  1507    1 779    4    81    87    178    3    31    54    80'
		text_table[i] <- x
	}
	if(semana==37 && anho==2015) {
		i <- 2;
		x <- 'Baja California    58    442  1549    1848    6    86    88    184    1    32    54    85'
		text_table[i] <- x
	}
	if(semana==38 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    46    455   1030    543    -    17    12    8    -    3    8    2'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    41    455   1577    1923    2    87    89    189    -    32    54    87'
		text_table[i] <- x
	}
	if(semana==39 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    69    471   1089    559    1    19    13    8    -    3    8    2'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    62    467   1627    1963    9    92    93    197    4    36    54    90'
		text_table[i] <- x
	}
	if(semana==40 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    57    486   1131    576    5    23    14    8    1    3    9    2'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    58    473   1679    2033    4    94    95    206    3    37    56    94'
		text_table[i] <- x
	}
	if(semana==41 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    44    495   1166    607    2    24    15    8    -    3    9    2'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    60    486   1726    2088    8    99    98    210    4    40    57    94'
		text_table[i] <- x
	}
	if(semana==42 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    43    505   1199    639    -    24    15    8    1    3    10    2'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    63    503   1772    2144    2    100    99    216    4    41    60    98'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    400    3286   10197    10599    8    188    199    165    3    51    57    87'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    91    829   2820    1615    10    129    106    78    -    24    29    16'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    56    384   1405    199    6    84    53    46    -    23    21    9'
		text_table[i] <- x
	}
	if(semana==43 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    51    518   1237    668    1    20    15    10    -    3    10    4'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    68    518   1825    2213    6    104    101    222    3    42    62    103'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    395    3389   10510    10888    16    196    208    169    3    53    58    89'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    61    856   2878    1705    6    131    110    81    2    24    31    18'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    18    389   1418    209    3    85    55    47    -    23    21    9'
		text_table[i] <- x
	}
	if(semana==44 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    47    529    1273    704    1    20    16    11    -    3    9    4'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    55    531   1867    2275    8    108    103    231    3    42    65    105'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    305    3468   10736    11185    11    201    214    170    5    55    61    89'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    173    892   3020    1789    4    134    111    83    -    24    31    18'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    43    400    1451    213    3    88    55    49    -    23    21    9'
		text_table[i] <- x
	}
  # Hasta aqui voy
  # Hasta aqui voy
  # Hasta aqui voy
  # Hasta aqui voy
  # Hasta aqui voy
	if(semana==45 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    43    540   1308    751    -    20    16    11    2    3    11    4'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    58    545   1911    2336    8    111    107    236    2    43    66    107'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    291    3541   10989    11436    18    212    221    176    6    57    65    91'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    45    905   3052    1848    3    137    111    83    1    25    31    18'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    13    404   1460    222    4    89    58    51    3    25    22    9'
		text_table[i] <- x
	}
	if(semana==46 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    60    549   1359    799    1    20    17    11    1    3    12    5'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    49    556   1949    2394    6    114    110    246    4    46    67    110'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    323    3617   11238    11688    18    222    230    186    -    57    65    91'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    82    939   3142    1917    5    142    114    83    1    25    32    18'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    25    408   1481    233    5    89    63    52    1    25    23    9'
		text_table[i] <- x
	}
	if(semana==47 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    38    556   1390    833    -    20    17    11    -    3    12    5'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    52    566   1991    2455    4    114    114    252    3    47    69    115'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    293    3676   11488    11918    13    228    237    190    1    57    66    92'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    93    969    3238    1982    4    144    117    84    1    25    33    19'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    24    415   1498    246    2    91    63    57    1    26    23    9'
		text_table[i] <- x
	}
	if(semana==48 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    30    557   1416    864    -    20    17    12   1    3    13    6'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    44    580   2021    2490    5    115    118    255   1    47    70    117'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    314    3757    11721    12170    14    235    244    192   1    58    66    92'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    70    993   3293    2024    10    151    120    86   3    27    34    19'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    17    419    1511    257    4    93    65    57   3    28    24    9'
		text_table[i] <- x
	}
	if(semana==49 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    44    516    1315    893    2    21    18    13    1    3    14    6'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    50    591   2060    2536    8    119    122    260    -    47    70    117'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    332    3860    11950    12411    7    238    248    196    4    59    69    92'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    97    1021     3363    2100    1    153    121    87    3    27    37    19'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    20    424     1526    266    4    96    66    57    4    30    26    9'
		text_table[i] <- x
	}
	if(semana==50 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    49    526    1355    914    1    22    18    15    -    3    14    7'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    52    614    2089    2587    2    121    121    270    1    48    70    118'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    299    3921     12187    12648    13    245    254    200    3    60    71    93'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    89    1045    3428    2176    3    155    122    89    1    28    37    19'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    30    433     1547    289    4    99    67    57    1    31    26    9'
		text_table[i] <- x
	}
	if(semana==51 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    67    602    1540    944    -    22    18    15    1    3    15    7'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    44    622   2125    2644    6    123    125    275    3    49    72    120'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    271    3985    12394    12843    11    254    256    207    3    60    74    93'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    41    1051    3463    2205    2    156    123    96    1    28    38    19'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    14    435   1559    292    1    99    68    57    1    32    26    9'
		text_table[i] <- x
	}
	if(semana==52 && anho==2015) {
		i <- 1;
		x <- 'Aguascalientes    20    606    1556    978    1    23    18    15    -    3    15    7'
		text_table[i] <- x
		i <- 2;
		x <- 'Baja California    24    631    2140    2702    2    124    126    281    -    49    72    123'
		text_table[i] <- x
		i <- 9;
		x <- 'Distrito Federal    175    4023    12531    13013    5    257    258    209    4    62    76    93'
		text_table[i] <- x
		i <- 10;
		x <- 'Durango    26    1069    3508    2272    4    159    124    99    3    29    40    19'
		text_table[i] <- x
		i <- 12;
		x <- 'Guerrero    10    436    1568    293    3    101    69    57    -    32    26    9'
		text_table[i] <- x
	}
	return(text_table)
}
